### ISSUE TITLE
RecursionError

### ISSUE THREAD

**Issue by JulienPalard** [aroberge/friendly-traceback#65] opened 2020-07-30 14:27 UTC
Seen this one today:

```
## Python exception

    :::pytb
    Traceback (most recent call last):
      File "solution.py", line 1, in <lambda>
        fibonacci = lambda n,f=[1,1]: n==1 and [1] or n-2 and fibonacci(n-1,f+[f[-1]+f[-2]]) or f
      File "solution.py", line 1, in <lambda>
        fibonacci = lambda n,f=[1,1]: n==1 and [1] or n-2 and fibonacci(n-1,f+[f[-1]+f[-2]]) or f

[hundred of identical lines, truncated by me for the readability of the issue]

      File "solution.py", line 1, in <lambda>
        fibonacci = lambda n,f=[1,1]: n==1 and [1] or n-2 and fibonacci(n-1,f+[f[-1]+f[-2]]) or f
      File "solution.py", line 1, in <lambda>
        fibonacci = lambda n,f=[1,1]: n==1 and [1] or n-2 and fibonacci(n-1,f+[f[-1]+f[-2]]) or f
      File "solution.py", line 1, in <lambda>
        fibonacci = lambda n,f=[1,1]: n==1 and [1] or n-2 and fibonacci(n-1,f+[f[-1]+f[-2]]) or f
      File "solution.py", line 1, in <lambda>
        fibonacci = lambda n,f=[1,1]: n==1 and [1] or n-2 and fibonacci(n-1,f+[f[-1]+f[-2]]) or f
      File "solution.py", line 1, in <lambda>
        fibonacci = lambda n,f=[1,1]: n==1 and [1] or n-2 and fibonacci(n-1,f+[f[-1]+f[-2]]) or f
      File "solution.py", line 1, in <lambda>
        fibonacci = lambda n,f=[1,1]: n==1 and [1] or n-2 and fibonacci(n-1,f+[f[-1]+f[-2]]) or f
      File "solution.py", line 1, in <lambda>
        fibonacci = lambda n,f=[1,1]: n==1 and [1] or n-2 and fibonacci(n-1,f+[f[-1]+f[-2]]) or f
      File "solution.py", line 1, in <lambda>
        fibonacci = lambda n,f=[1,1]: n==1 and [1] or n-2 and fibonacci(n-1,f+[f[-1]+f[-2]]) or f
      File "solution.py", line 1, in <lambda>
        fibonacci = lambda n,f=[1,1]: n==1 and [1] or n-2 and fibonacci(n-1,f+[f[-1]+f[-2]]) or f
      File "solution.py", line 1, in <lambda>
        fibonacci = lambda n,f=[1,1]: n==1 and [1] or n-2 and fibonacci(n-1,f+[f[-1]+f[-2]]) or f
    RecursionError: maximum recursion depth exceeded in comparison

No information is known about this exception.
Please report this example to
https://github.com/aroberge/friendly-traceback/issues


### Execution stopped on line 1 of file '~/solution.py'.

    :::text
        -->1: fibonacci = lambda n,f=[1,1]: n==1 and [1] or n-2 and fibonacci(n-1,f+[f[-1]+f[-2]]) or f


#### Variables

    :::text
        global fibonacci: <function <lambda>>
        n: 0
        f: [1, 1]


### Exception raised on line 1 of file '~/solution.py'.


    :::text
        -->1: fibonacci = lambda n,f=[1,1]: n==1 and [1] or n-2 and fibonacci(n-1,f+[f[-1]+f[-2]]) or f


#### Variables:

    :::text
        global fibonacci: <function <lambda>>
        n: -997
        f: [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 2...]  | len(f): 999
```

**Comment by aroberge** [comment] 2020-07-30 14:32
Thanks. I knew I had to eventually include this case. Good time to work on it now that I have a report from actual user code.

**Comment by aroberge** [comment] 2020-07-30 15:49
This is weird. I just created a test case and the output looks very different from yours.
![image](https://user-images.githubusercontent.com/629698/88944309-f3f88580-d262-11ea-97fc-fcc78693832f.png)

**Comment by JulienPalard** [comment] 2020-07-30 15:52
Is it because I use my own formatter:
<details>
<summary>
my formatter
</summary>

```python
def friendly_traceback_markdown(info, level):                                                                                                                  
    """Traceback formatted with full information but with markdown syntax."""                                                                                  
    result = []                                                                                                                                                
    friendly_items = [                                                                                                                                         
        ("header", "## ", "\n", ""),                                                                                                                           
        ("simulated_python_traceback", "", "\n", "pytb"),                                                                                                      
        ("generic", "", "\n", ""),                                                                                                                             
        ("parsing_error", "\n", "\n", ""),                                                                                                                     
        ("parsing_error_source", "", "", "text"),                                                                                                              
        ("cause_header", "### ", "\n", ""),                                                                                                                    
        ("cause", "", "\n", ""),                                                                                                                               
        ("last_call_header", "### ", "", ""),                                                                                                                  
        ("last_call_source", "", "", "text"),                                                                                                                  
        ("last_call_variables", "\n#### Variables\n\n", "", "text"),                                                                                           
        ("exception_raised_header", "\n### ", "\n", ""),                                                                                                       
        ("exception_raised_source", "", "", "text"),                                                                                                           
        ("exception_raised_variables", "\n#### Variables:\n\n", "", "text"),                                                                                   
    ]                                                                                                                                                          
                                                                                                                                                               
    for item, prefix, suffix, pygment in friendly_items:                                                                                                       
        if item in info:                                                                                                                                       
            line = info[item]                                                                                                                                  
            if not isinstance(line, str):                                                                                                                      
                line = "\n".join(line)                                                                                                                         
            if item == "simulated_python_traceback":                                                                                                           
                line = line.replace("Simulated Traceback", "Traceback")                                                                                        
            if prefix[:1] == "#":                                                                                                                              
                line = line.rstrip(": ")  # Do not end titles with column                                                                                      
            if pygment:                                                                                                                                        
                line = "    :::" + pygment + "\n" + indent(line, "    ")                                                                                       
            result.append(prefix + line + suffix)                                                                                                              
    return "\n".join(result)                                                                                                                                   
```

probably because I use `simulated_python_traceback` instead of `python_traceback`? I bet this is the difference between the two?

**Comment by aroberge** [comment] 2020-07-30 15:58
Here's using the same option as you do, I think ...
![image](https://user-images.githubusercontent.com/629698/88945408-5605ba80-d264-11ea-867a-b3a524fed50b.png)

**Comment by aroberge** [comment] 2020-07-30 16:08
The markdown formatter included with friendly_traceback was missing the "generic" field, which is why there's no mention of reporting this case in the last screenshot I posted; this has been fixed.

**Comment by aroberge** [comment] 2020-07-30 16:22
Weird, I tried with your code and it does produce a huge amount of lines; something is weird...

**Comment by JulienPalard** [comment] 2020-07-30 16:38
Looks like `--level` is ignored, I'm digging (but may not have a lot of time, time to cook soon :p)

**Comment by aroberge** [comment] 2020-07-30 16:40
I'm digging too, and will try to take care of it.

**Comment by JulienPalard** [comment] 2020-07-30 16:43
Looks like `.install()` reset the level in __main__.py:
```
(Pdb) p public_api.get_level()
7
(Pdb) n
> /home/mdk/clones/JulienPalard/correction-helper/.venv/lib/python3.8/site-packages/friendly_traceback/__main__.py(146)main()
-> public_api.install()
(Pdb) 
> /home/mdk/clones/JulienPalard/correction-helper/.venv/lib/python3.8/site-packages/friendly_traceback/__main__.py(148)main()
-> if args.formatter:
(Pdb) p public_api.get_level()
1
```

**Comment by aroberge** [comment] 2020-07-30 16:46
level is, I believe, a red-herring: it is currently used simply to
determine what default formatter is used - each formatter has its own list
of information shown.
The shortening of the traceback into a few lines is done elsewhere.

**Comment by JulienPalard** [comment] 2020-07-30 16:50
Something like this should do: https://github.com/JulienPalard/friendly-traceback/commit/fc852f6abee8d2844d9a0517e74b0e86a9bc0fff

But I don't think this is good, we should maybe do it the other way: `.install()` with no parameter should not touch the level.

But I let you choose, I don't know if someone relies on `public_api.install()` re-initializing the level or not.

SIGMIAM

**Comment by aroberge** [comment] 2020-07-30 17:01
Got it.  I should change a `>=` sign to `=` in the documentation/help, and add a bit of extra information.

First, the info about verbosity as included
```
        Note: the values of the verbosity level described below are:
            0: Normal Python tracebacks
            1: Default - does not need to be specified
            2: Python tracebacks appear before the friendly display
            3: Python tracebacks appended at the end of the friendly display.
            4: Python traceback followed by basic explanation
            5: Only basic explanation
            6: No generic explanation
            7: Python tracebacks appear before the friendly display but
               no generic explanation is included.
            9: Python traceback

        The Python traceback for level >= 1 are the simulated version.
        You can use negative values to show the true Python traceback which
        will likely include function calls from friendly-traceback itself.
        Thus level -9 is equivalent to level 0.
```

By default (value == 1), the Python traceback are *not* shown; this is using the formatters included.  All the information is always computed, and it is up to the formatter to decide what information is shown.
- I chose this default as I extracted what I thought to be the only relevant part to show to the user.
- Other choices, that include the Python tracebacks, are there for people to learn to understand how to read a normal Python traceback, and see that much of the information extracted by friendly-traceback is in a normal traceback.

In your formatter, you have chosen to include the Python traceback. If you suppress that line, or add something like:
```python
if item == "simulated_python_traceback":
    line = line.replace("Simulated Traceback", "Traceback")
    if len(line) > 200:
        line = line[1:200] + "..."
```

**Comment by aroberge** [comment] 2020-07-30 18:00
Regarding the Python traceback: the true Python traceback is available by using `info["python_traceback"]`; see https://github.com/aroberge/friendly-traceback/blob/master/friendly_traceback/core.py#L172
```
   for item in python_tb:
        temp.append(item.rstrip())
    info["python_traceback"] = python_tb = temp
```
Another option for your formatter is to exclude it only in the case of RecursionError - this string would likely be found in `info["message"]`

**Comment by aroberge** [comment] 2020-07-30 20:48
I'm going to close this as this is not a bug: including the Python traceback (simulated or not) does result in this kind of output. 
I have changed the help text shown by argparse in an attempt to make it clearer that the default level does not include the Python traceback.   I will add an issue on the documentation site about explaining this when discussing custom formatters.

**Comment by aroberge** [comment] 2020-07-30 21:10
Reopening as I still have to add an explanation about the meaning of a RecursionError

**Comment by aroberge** [comment] 2020-08-01 11:25
Test case and explanation for RecursionError added in latest commit. Closing this issue.

**Closed by aroberge** 2020-08-01 11:25 UTC
Labels: New case

**Comment by aroberge** [comment] 2020-08-24 01:19
This issue is closed, but handling of this case has changed.

The traceback for recursion error has been significantly improved. The true Python traceback truncates correctly something arising from
```def a():
   a()
a()
```
However, it fails miserably (printing out 1000 lines) for something like
```
def a():
   b()
def b():
   a()
a()
```

whereas the new "simulated" traceback gives
```

    Traceback (most recent call last):
      File "<friendly-console:3>", line 1, in <module>
      File "<friendly-console:1>", line 2, in a
           ... Many other lines. ...
      File "<friendly-console:1>", line 2, in a
      File "<friendly-console:2>", line 2, in b
      File "<friendly-console:1>", line 2, in a
      File "<friendly-console:2>", line 2, in b
      File "<friendly-console:1>", line 2, in a
      File "<friendly-console:2>", line 2, in b
    RecursionError: maximum recursion depth exceeded
```
